/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author USER
 */
public class FormKondisi extends javax.swing.JFrame {
public java.sql.Statement st;
    /**
     * Creates new form FormKategori
     */
    public FormKondisi() {
        initComponents();
        tampilTable();
        combobox();
        disposeTxtid();
    }
    
      public void disposeTxtid(){
        labelId.setVisible(false);
        txtId.setVisible(false);
    }
    
    public void showTxtId(){
    labelId.setVisible(true);
    txtId.setVisible(true);
    txtId.setEditable(false);
}
    
    public void reset(){
        txtId.setText("");
        txtKdBuku.setSelectedIndex(0);
        txtKet.setText("");
        disposeTxtid();
    }
    
    private DefaultTableModel tabmode;
    public void tampilTable() {
      Object[] baris = {"Judul", "kode Buku", "Keterangan Kondisi"};
        tabmode = new DefaultTableModel(null, baris);
        String sql = "SELECT buku.judul, kondisi.kd_buku, kondisi.keterangan "
                + "FROM kondisi INNER JOIN buku ON kondisi.kd_buku = buku.kd_buku;";
        
       jTable2.setModel(tabmode);
        try {
            Connection konek = new koneksi().getKoneksi();

            st = konek.createStatement();
            ResultSet hasil = st.executeQuery(sql);
            
            while(hasil.next()){
                
                String judul = hasil.getString("judul");
                String kd_buku = hasil.getString("kd_buku");
                String keterangan = hasil.getString("keterangan");
                String []data = {judul, kd_buku, keterangan};

                tabmode.addRow(data);

            }
            tabmode.fireTableDataChanged();
            konek.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "gagal menampilkan data! Error: " + e.getMessage());
}

}
    
    public void combobox(){
        try {
        Connection konek = new koneksi().getKoneksi();
        st = konek.createStatement();
        String sql = "SELECT kd_buku from buku";
        ResultSet hasil = st.executeQuery(sql);
        while (hasil.next()) {
            Object[] obj = new Object[1];
            obj[0] = hasil.getString(1);
            txtKdBuku.addItem((String) obj[0]);
        }
        hasil.close(); st.close();
        } catch (SQLException e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(null, "gagal menampilkan combobox! Error: " + e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        labelId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtKdBuku = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBuku = new javax.swing.JMenu();
        menuKondisi = new javax.swing.JMenu();
        menuPenyimpanan = new javax.swing.JMenu();
        menuKategori = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 122, 0, 0));

        jPanel1.setBackground(new java.awt.Color(101, 40, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(573, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(160, 118, 249));

        jButton3.setBackground(new java.awt.Color(204, 153, 0));
        jButton3.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(237, 228, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        labelId.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        labelId.setForeground(new java.awt.Color(237, 228, 255));
        labelId.setText("ID Kondisi");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 228, 255));
        jLabel2.setText("Kode Buku");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 228, 255));
        jLabel3.setText("Keterangan");

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(237, 228, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 51, 0));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(237, 228, 255));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtKet.setColumns(20);
        txtKet.setRows(5);
        jScrollPane2.setViewportView(txtKet);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kondisi", "Kode Buku", "Keterangan"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 228, 255));
        jLabel4.setText("Form Kondisi Buku");

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtId)
                            .addComponent(txtKdBuku, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtKdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        menuBuku.setText("Data Buku");
        menuBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBukuMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBuku);

        menuKondisi.setText("Data Kondisi");
        menuKondisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKondisiMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuKondisi);

        menuPenyimpanan.setText("Data Penyimpanan");
        menuPenyimpanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPenyimpananMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuPenyimpanan);

        menuKategori.setText("Data Kategori");
        menuKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKategoriMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuKategori);

        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        reset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
             Connection konek = new koneksi().getKoneksi();
            st = konek.createStatement();
            
            String keterangan = this.txtKet.getText();
            String kd_buku = this.txtKdBuku.getSelectedItem().toString();
            
            
             String insert = "INSERT INTO kondisi (kd_buku, keterangan) values ('"+kd_buku+"','"+keterangan+"')";
             st.executeUpdate(insert);
             reset();
             tampilTable();
             
            JOptionPane.showMessageDialog(null, "Kondisi Buku Berhasil Ditambahkan!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal menambahkan Kondisi buku, Error : "+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        txtKdBuku.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        txtKet.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        
        Connection konek = new koneksi().getKoneksi();
   try {
        st = konek.createStatement();
        String query = "SELECT id FROM kondisi WHERE kd_buku = '" + txtKdBuku.getSelectedItem().toString()+ "'";
        ResultSet hasil = st.executeQuery(query);
        int id = 0;
        if (hasil.next()) {
            id = hasil.getInt("id");
        }
        txtId.setText(String.valueOf(id)); 

        showTxtId();
    } catch (SQLException ex) {
        Logger.getLogger(FormKategori.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id = txtId.getText();
       if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "silahkan pilih data terlebih dahulu!");
        }else{
            int jawaban = JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin menghapus ? ");
            if(jawaban == 0){
                try {
                   Connection konek = new koneksi().getKoneksi();
                   st = konek.createStatement();
                   String sql = "DELETE FROM kondisi WHERE id ='"+id+"';";
                   st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Kondisi Buku berhasil dihapus!");
                    reset();
                    tampilTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Kondisi Buku gagal dihapus!, error"+e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = txtId.getText();
        String kd_buku = txtKdBuku.getSelectedItem().toString();
        String ket = txtKet.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(this, "silahkan pilih data terlebih dahulu!");
        }else{
            int jawaban = JOptionPane.showConfirmDialog(null, "apakah anda yakin ingin Mengedit Data ? ");
            if(jawaban == 0){
                try {
                   Connection konek = new koneksi().getKoneksi();
                    st = konek.createStatement();
              
                   String sql = "UPDATE kondisi SET kd_buku = '"+kd_buku+"', keterangan = '"+ket+"' WHERE id = '"+id+"';";
                   st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Kondisi Buku berhasil diedit!");
                    reset();
                    tampilTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Kondisi Buku gagal diedit!, error"+e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBukuMouseClicked
        new form.FormData().show();
        this.dispose();
    }//GEN-LAST:event_menuBukuMouseClicked

    private void menuKondisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKondisiMouseClicked
        new form.FormKondisi().show();
        this.dispose();
    }//GEN-LAST:event_menuKondisiMouseClicked

    private void menuPenyimpananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenyimpananMouseClicked
        new form.FormPenyimpanan().show();
        this.dispose();
    }//GEN-LAST:event_menuPenyimpananMouseClicked

    private void menuKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKategoriMouseClicked
        new form.FormKategori().show();
        this.dispose();
    }//GEN-LAST:event_menuKategoriMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        new form.formLogin().show();
        this.dispose();
    }//GEN-LAST:event_menuLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKondisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelId;
    private javax.swing.JMenu menuBuku;
    private javax.swing.JMenu menuKategori;
    private javax.swing.JMenu menuKondisi;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenu menuPenyimpanan;
    private javax.swing.JTextField txtId;
    private javax.swing.JComboBox<String> txtKdBuku;
    private javax.swing.JTextArea txtKet;
    // End of variables declaration//GEN-END:variables
}
